default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres
  port: 5433

development:
  <<: *default
  database: oiv-ui-dev

test:
  <<: *default
  database: oiv-ui-test
